baseURL = 'https://gppmad.github.io/'
languageCode = 'en-us'
title = "Blog"
theme = 'PaperMod'

[params]
author = "Giuseppe Maddiona"
description = "Blog"
defaultTheme = "light"
disableThemeToggle = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
mainSections = ["posts"]
disableSpecial1stPost = true
hideAuthor = true

[[params.socialIcons]]
name = "github"
url = "https://github.com"
